### PR TITLE
Fix PyPi deployment issue

### PR DESCRIPTION
**Pull request by Myoldmopar**
I was half expecting PyPi to complain about the new package name, but instead, the preprocessor complained about the contents of the long_description which is used on the package page on PyPi.  I was seeing one small "error" in the readme, so I fixed that...let's see.

### CODE REVIEW

**Comment by mitchute** [comment]
You can nix all that if you don't get it working in another 30 seconds...

**Comment by Myoldmopar** [comment]
From the PyPi distribution script:

```
Checking dist/energyplus_diff_analysis-0.2-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         line 80: Warning: Inline literal start-string without end-string.      
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
```

* checks long description, no issues, what in the world!? *

Then from https://github.com/pypa/twine/issues/454#issuecomment-464077386:

> The issue is that the multiple lines in your License field are causing the rest of the file to be interpreted as the Long-Description. This field should not be your entire license text, it should be just "MIT License", and you should include a LICENSE file in your distribution.

Ahh of course.  That was so obvious from twine.  The license name has multiple lines.

**Comment by Myoldmopar** [comment]
Good to go: https://pypi.org/project/energyplus-diff-analysis/0.2/

**Comment by Myoldmopar** [comment]
I'll let CI finish, but this is good to go now that v0.2 has been packaged and deployed to PyPi.

**Pull request merged**
